all:
	javac -d ../bin RPiRTTY.java
	javac -d ../bin SoundController.java
	javac -d ../bin KeyStatus.java
	javac -d ../bin SoundMachine.java
	javac -d ../bin SineGen.java
	javac -d ../bin DoubleSineGen.java
