all:
	../../Downloads/jdk1.7.0_79/bin/javac RPiRTTY.java
	../../Downloads/jdk1.7.0_79/bin/javac SoundController.java
	../../Downloads/jdk1.7.0_79/bin/javac KeyStatus.java
	../../Downloads/jdk1.7.0_79/bin/javac SoundMachine.java
	../../Downloads/jdk1.7.0_79/bin/javac SineGen.java
	../../Downloads/jdk1.7.0_79/bin/javac DoubleSineGen.java

mac:
	javac RPiRTTY.java
	javac SoundController.java
	javac KeyStatus.java
	javac SoundMachine.java
	javac SineGen.java
	javac DoubleSineGen.java

old:
	javac  RPiRTTY.java
	javac SoundController.java
